### ISSUE TITLE
Incompatability with Tinkers’ Construct and Botania (liquids not rendering)

### ISSUE THREAD

**Issue by Nevrai** [Asek3/Oculus#150]
Shaders don’t work properly with the [Tinkers’ Construct](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct) mod:

1. Liquids in the smeltery are not rendered.
2. Lava in the seared fuel tank or seared melter are not rendered.
3. Liquids drained from the smeltery or melter into a casting table or casting basin are not rendered.

### Screenshots
<details>
  <summary>Comparison screenshots (click to expand)</summary>
  
#### Shaders off
![2022-08-11_22 06 37](https://user-images.githubusercontent.com/59761487/184233781-3a7fb000-9cff-4e9e-9443-908412f219ff.png)

#### Shaders on
![2022-08-11_22 06 35](https://user-images.githubusercontent.com/59761487/184233787-1715b7aa-6215-4ea1-a13b-0d4652c47f08.png)

#### Shaders off
![2022-08-11_22 13 24](https://user-images.githubusercontent.com/59761487/184233833-76773e5f-3001-4e7b-a0d1-44a079dfb80c.png)

#### Shaders on
![2022-08-11_22 13 22](https://user-images.githubusercontent.com/59761487/184233839-d1543a5e-6b1d-41bb-9d0a-3a16176c1e63.png)

  
</details>

Tested with [Complementary Shaders v4](https://www.curseforge.com/minecraft/customization/complementary-shaders), [Complementary Reimagined](https://www.curseforge.com/minecraft/customization/complementary-reimagined), and [SEUS Renewed](https://www.sonicether.com/seus/), but the same issue occurs with all shader packs. This is not an issue when using OptiFine for shaders (or at least it wasn’t back in 1.12.2, but I haven’t tested it in 1.18.2 since I couldn’t get OptiFine to work).

Tested without any mods except Tinkers’ Construct, Mantle (Tinkers’ dependency), Rubidium, and Oculus. I submitted this on the Tinkers’ Construct issue tracker first (SlimeKnights/TinkersConstruct/issues/4968) but was told that this is an issue on Oculus’ end.

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Oculus:** 1.2.5a (latest)
* **Rubidium:** 0.5.3a (latest)
* **Tinkers’ Construct:** 3.5.1.31 (latest)
* **Mantle:** 1.9.27 (latest)
* **Java:** 17 (OpenJDK Platform Library, version 17.0.1.0)
* **OS:** Windows 11 Home, version 21H2
* **GPU:** NVIDIA GeForce RTX 3070 Laptop GPU

**Comment by Nevrai** [comment]
I have noticed that the same issue occurs with [Botania](https://www.curseforge.com/minecraft/mc-mods/botania): mana is not rendered in mana pools when using Oculus with shaders enabled. Sparks above mana pools or other blocks are not rendered either.

### Shaders off

![2022-08-16_03 10 20](https://user-images.githubusercontent.com/59761487/184773653-d75709b4-1790-4f5e-a284-2cf0f41ee6a6.png)

### Shaders on
![2022-08-16_03 10 25](https://user-images.githubusercontent.com/59761487/184773701-f4c4096b-d663-440f-95d1-dfe166d9699a.png)

**Botania version:** 434 (latest for 1.18.2)

**Comment by maddiemort** [comment]
I'm also having this problem on 1.18.2, only when shaders are enabled.

**Comment by Nevrai** [comment]
I’ve resorted to toggling my shaders off every time I’m dealing with Botania or Tinkers’ Construct. I hope this is something that the Oculus team can fix.

**Comment by KHanafi1100** [comment]
This has also been happening to me, and I can only hope this can be fixed soon otherwise I might need to either change to optifine or play without shaders. And I would rather not have to do either of those two things.

**Comment by urikkiru** [comment]
This is something that is also affecting me. Just out of curiosity I loaded up a 1.16.5 modpack(Enigmatica 6) and lava was definitely rendering in that version inside of Tinker's Construct tanks while running Oculus 1.2.6 for 1.16.5. Given that the 1.18.2 version of Oculus is still on 1.2.5a, perhaps this is something that is fixed in 1.2.6 and we simply need for that version to be released for 1.18.2?

**Comment by Lolothepro** [comment]
>This is something that is also affecting me. Just out of curiosity I loaded up a 1.16.5 modpack(Enigmatica 6) and lava was definitely rendering in that version inside of Tinker's Construct tanks while running Oculus 1.2.6 for 1.16.5. Given that the 1.18.2 version of Oculus is still on 1.2.5a, perhaps this is something that is fixed in 1.2.6 and we simply need for that version to be released for 1.18.2?

This issue is not fixed in Iris 1.2.6

**Comment by DeleteMetaInf** [comment]
Liquids are also not rendered in [Hexerei](https://www.curseforge.com/minecraft/mc-mods/hexerei)’s mixing cauldron or [Ex Nihilo: Sequentia](https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia)’s barrels or crucibles.

**Comment by Nevrai** [comment]
Liquids are also not rendered in [Hexerei](https://www.curseforge.com/minecraft/mc-mods/hexerei)’s mixing cauldron or [Ex Nihilo: Sequentia](https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia)’s barrels or crucibles with shaders enabled—also in 1.18.2, Forge.

**Comment by Asek3** [comment]
Tinkers' smeltery was fixed, Botania can't be fixed due to how Iris works

**Comment by c8j** [comment]
Still have issues with Oculus 1.6.9a on 1.19.2 with Tinkers molten metals turning transparent when the cooling animation happens, fading to visible again. Happens even if I disable the shader pack, it's enough just to have oculus installed.
